version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - Dheyson
  - AtilaAssuncao
  assignees:
  - AtilaAssuncao
  labels:
  - enhancement
  ignore:
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.21.0
  - dependency-name: sucrase
    versions:
    - 3.17.0
